"""The tracked catalog rendered twice, without a VM: the default (no local.json: lab, English)
and a personal local.json (identity + locale block). Every profile of an unattended flow has
its answer files and kernel line generated by vmctl's own renderers, then checked against the
rules the live runs taught. The night matrix of 2026-09-29/30 lost 30 rows to one of them
(language=it on the d-i kernel line, over the serial console): this test is the cheap guard.

Seconds, not hours: no QEMU, no ISO, no guest. Keys are fake and nothing is written outside
the temporary root.
"""
import shlex
import shutil
from unittest import mock

from tests._common import BaseVmctlTestCase, ROOT
from vmctl import (alpine, archinstall, autoyast, cloud_init, config, kickstart, lifecycle, opnsense, preseed,
                   slackware, ssh, ubiquity, windows)

PROBE_USER = "vmctlprobe"
LOCALE = {"language": "it_IT.UTF-8", "keyboard": "it", "timezone": "Europe/Rome"}
PERSONAL = {"identity": {"user": PROBE_USER, "password": "probe-pass",
                         "password_hash": "$6$probe$abcdefghijklmnopqrstuv", "realname": "Probe User"},
            "locale": LOCALE, "vms": {}}
FAKE_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPROBEKEYPROBEKEYPROBEKEYPROBEKEYPROBE vmctl-probe"

# Kernel lines read by an installer that talks over the serial console: ASCII only, and the
# installer's own language stays English (d-i asks "Language:" otherwise, 2026-09-30).
SERIAL_FLOWS = ("bootstrap-preseed", "bootstrap-kickstart", "bootstrap-autoyast", "bootstrap-archinstall")


def render(name: str, vm: dict) -> dict[str, str]:
    """What vmctl would write or boot for *vm*: kernel line and answer files, by flow."""
    flow = lifecycle.local_test_mode(vm)[0]
    out: dict[str, str] = {}
    if flow == "bootstrap-preseed":
        out["append"] = preseed.kernel_append(vm)
        out["preseed.cfg"] = preseed.render_preseed(name, vm)
        out["late_command.sh"] = preseed.render_late_command_script(name, vm)
    elif flow == "bootstrap-kickstart":
        out["append"] = kickstart.kernel_append(vm)
        out["ks.cfg"] = kickstart.render_kickstart(name, vm, ostree_ref="fedora/probe/x86_64/silverblue")
    elif flow == "bootstrap-autoyast":
        out["append"] = autoyast.kernel_append(vm)
        out["autoinst.xml"] = autoyast.render_autoyast(name, vm)
    elif flow == "bootstrap-archinstall":
        out["append"] = archinstall.live_kernel_append(vm, "ARCH_PROBE")
        out["install.sh"] = archinstall.render_bootstrap_script(name, vm)
    elif flow == "bootstrap-alpine":
        out["answerfile"] = alpine.render_answerfile(name, vm)
        out["install.sh"] = alpine.render_install_script(name, vm)
    elif flow == "bootstrap-slackware":
        out["install.sh"] = slackware.render_install_script(name, vm, [FAKE_KEY])
    elif flow == "bootstrap-unattended":
        out["user-data"] = cloud_init.render_autoinstall_user_data(name, vm, dry_run=True)
    elif flow == "bootstrap-ubiquity":
        out["append"] = ubiquity.kernel_append(vm)
        out["seed"] = ubiquity.render_seed(name, vm)
    elif flow == "bootstrap-opnsense":
        out["config.xml"] = opnsense.render_config_xml(name, vm, [FAKE_KEY], password_hash="$2y$10$probe")
    elif flow == "bootstrap-windows" and windows.windows_config(vm) is not None:
        out["autounattend.xml"] = windows.render_autounattend(name, vm)
    return out


class LocaleRenderingTests(BaseVmctlTestCase):
    def setUp(self):
        super().setUp()
        profiles = self.config_dir / "profiles"
        shutil.rmtree(profiles, ignore_errors=True)
        profiles.mkdir(parents=True)
        for path in (ROOT / "vms" / "profiles").glob("*.json"):
            if not path.name.startswith("local"):
                shutil.copy(path, profiles / path.name)
        key = self.root / "probe.pub"
        key.write_text(FAKE_KEY + "\n")
        for target, value in ((ssh, "resolve_ssh_public_key"), (cloud_init, "_authorized_keys_for_vm")):
            patcher = mock.patch.object(target, value, return_value=key if value == "resolve_ssh_public_key" else [FAKE_KEY])
            patcher.start()
            self.addCleanup(patcher.stop)

    def rendered(self, local):
        cfg = config.load_config(local_profiles=local)
        tracked = set(config.load_tracked(self.config_dir / "profiles"))
        out = {}
        for name in sorted(tracked):
            vm = cfg["vms"][name]
            try:
                files = render(name, vm)
            except Exception as exc:  # noqa: BLE001 - the test reports which profile broke and how
                self.fail(f"{name}: rendering failed: {type(exc).__name__}: {exc}")
            if files:
                out[name] = (vm, files)
        return out

    def test_every_unattended_profile_renders_in_both_variants(self):
        default, personal = self.rendered({"vms": {}}), self.rendered(PERSONAL)
        self.assertGreater(len(default), 80)  # the renderers above cover most of the catalog
        self.assertEqual(sorted(default), sorted(personal))

    def test_serial_console_kernel_lines_stay_ascii_and_english(self):
        for variant in ({"vms": {}}, PERSONAL):
            for name, (vm, files) in self.rendered(variant).items():
                append = files.get("append")
                if append is None or lifecycle.local_test_mode(vm)[0] not in SERIAL_FLOWS:
                    continue
                with self.subTest(name=name, personal=variant is PERSONAL):
                    self.assertTrue(append.isascii(), append)
                    self.assertNotIn("it_IT", append)
                    if lifecycle.local_test_mode(vm)[0] == "bootstrap-preseed":
                        self.assertIn("language=en ", append)  # d-i's own language, never the guest's
                        self.assertIn("keymap=it ", append) if variant is PERSONAL else None

    def test_the_locale_block_reaches_every_section_in_its_format(self):
        for name, (vm, files) in self.rendered(PERSONAL).items():
            text = "\n".join(files.values())
            with self.subTest(name=name):
                for section, values in config.locale_values(LOCALE).items():
                    raw = config.load_tracked(self.config_dir / "profiles")[name].get(section)
                    if not isinstance(raw, dict) or name in ("haiku",):
                        continue
                    for key, value in values.items():
                        if key in raw and len(value) > 2:  # "it" alone is a substring of everything
                            self.assertIn(value, text, f"{section}.{key}")
                if "preseed.cfg" in files:
                    run = "bash -lc " + shlex.quote(config.preseed_locale_command(LOCALE["language"]))
                    self.assertEqual(files["late_command.sh"].count(run), 1)  # run once (the WARN message names it too)
                if "autounattend.xml" in files:
                    self.assertNotIn("<UILanguage>it-IT</UILanguage>", files["autounattend.xml"])  # the medium's language stays

    def test_the_default_carries_no_personal_locale_and_the_identity_reaches_every_flow(self):
        for name, (vm, files) in self.rendered({"vms": {}}).items():
            with self.subTest(name=name, variant="default"):
                self.assertNotIn(config.preseed_locale_command(LOCALE["language"]), files.get("late_command.sh", ""))
                self.assertNotIn(PROBE_USER, "\n".join(files.values()))
        for name, (vm, files) in self.rendered(PERSONAL).items():
            text = "\n".join(files.values())
            with self.subTest(name=name, variant="personal"):
                self.assertNotIn("{{user}}", text)
                if vm.get("haiku_config") is None and vm.get("proxmox_config") is None:
                    self.assertIn(PROBE_USER, text)
