// Optional browser regression: PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs node tests/webui_browser.mjs
// Uses a fixture API and a noVNC stub: no real VM, job or disk is touched.
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = fileURLToPath(new URL('../', import.meta.url));
const html = readFileSync(root + 'vmctl/web/index.html');
const catalog = JSON.parse(execFileSync('python3', ['-c', 'import json; from vmctl.webui import command_catalog; print(json.dumps(command_catalog()))'], { cwd: root }));
const machine = (name, extra = {}) => ({ name, label: 'Arch Linux + Noctalia 5', family:'arch', memory_mb:8192, cpus:4, firmware:'EFI', running:false, installed:true, prepared:true, install_label:'verified', install_detail:'Boot verified by post-install; installed by bootstrap-archinstall.', disk_host:'7.8G', disk_capacity:'32G', iso_source:'cached', ssh_port:2226, has_ssh:true, has_archinstall:true, unattended_flow:'bootstrap-archinstall', ...extra });
const state = { version:'0.4.0', vms:[machine('arch-noctalia',{running:true}),machine('debian-server'),machine('proxmox-ve',{family:'proxmox'}),machine('proxmox-ve-node2',{family:'proxmox'}),machine('alpine-ci',{installed:false,prepared:false,install_label:'no disk'})], labs:[{group:'proxmox-lab', members:['proxmox-ve','proxmox-ve-node2'],start_order:['proxmox-ve','proxmox-ve-node2'],addresses:{'proxmox-ve':'10.10.10.2/24','proxmox-ve-node2':'10.10.10.3/24'}},{group:'new-lab',members:['alpine-ci'],start_order:['alpine-ci']}] };
let requests = [], failRun = false, failState = false, sshLaunches = 0, overrideRevision = 1, savedOverride = {};
let jobStatus = 'completed', jobCommand = 'vmctl start arch-noctalia --headless --background', cancelRequests = [], failCancel = false, cancelResult = true;
let jobId = 'web:fixture', holdRun = false, releaseRun;
let screenDelay = 700;
let screenRequests = 0, failScreen = false, holdState = false, stateWaiters = [], dynamicVmJobs = false;
const profileBase = {name:'Arch Linux + Noctalia',memory_mb:8192,cpus:4};
const server = createServer(async (req,res) => {
  if (req.url === '/' || req.url.startsWith('/?')) { res.setHeader('Content-Type','text/html'); return res.end(html); }
  if (req.url === '/assets/distro-icons.svg') { res.setHeader('Content-Type','image/svg+xml'); return res.end(readFileSync(root+'vmctl/web/distro-icons.svg')); }
  if (req.url === '/assets/icons.js') { res.setHeader('Content-Type','text/javascript'); return res.end(readFileSync(root+'vmctl/web/icons.js')); }
  res.setHeader('Content-Type','application/json');
  if (req.url.includes('/screen.png?')) {
    screenRequests++;
    if (screenDelay) await new Promise(resolve=>setTimeout(resolve,screenDelay));
    if (failScreen) { res.statusCode=503; return res.end('{}'); }
    res.setHeader('Content-Type','image/svg+xml');
    return res.end(`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="768"><rect width="1024" height="768" fill="#111827"/><rect width="1024" height="38" fill="#263449"/><g fill="#bceedd" font-family="monospace" font-size="22"><text x="24" y="94">Arch Linux · console</text><text x="24" y="145">guest@arch-noctalia:~$ uptime</text><text x="24" y="186">Screen frame ${screenRequests}</text></g></svg>`);
  }
  if (req.url.endsWith('/ssh-terminal')) { sshLaunches++; return res.end(JSON.stringify({terminal:'fixture'})); }
  if (req.url.endsWith('/override')) {
    if (req.method === 'POST') { let body=''; for await (const chunk of req) body+=chunk; const data=JSON.parse(body); assert.equal(data.revision,String(overrideRevision)); savedOverride=data.override; overrideRevision++; }
    return res.end(JSON.stringify({name:'arch-noctalia',base:profileBase,effective:{...profileBase,...savedOverride},override:savedOverride,revision:String(overrideRevision),local_only:false}));
  }
  if (req.url.startsWith('/api/state')) { const body=JSON.stringify(failState ? {error:'fixture offline'} : state); if (holdState) await new Promise(resolve=>stateWaiters.push(resolve)); res.statusCode=failState ? 503 : 200; return res.end(body); }
  if (req.url === '/api/commands') return res.end(JSON.stringify(catalog));
  if (req.url === '/api/jobs') return res.end(JSON.stringify([{id:jobId,status:jobStatus,command:jobCommand,updated:1789900000}]));
  if (req.url.includes('/log?')) {
    const log = 'Fixture job output.\n', offset = Number(new URL(req.url,'http://fixture').searchParams.get('offset'));
    return res.end(JSON.stringify({text:log.slice(offset),offset:log.length,size:log.length,status:jobStatus}));
  }
  if (req.url.endsWith('/cancel')) {
    cancelRequests.push(req.url); res.statusCode = failCancel ? 500 : 200;
    if (!failCancel) jobStatus = cancelResult ? 'cancelled' : 'completed';
    if (!failCancel && jobId === 'vm:arch-noctalia') state.vms[0].running=false;
    return res.end(JSON.stringify(failCancel ? {error:'Fixture cancellation failed'} : {cancelled:cancelResult}));
  }
  if (req.url === '/api/catalog') {
    let body=''; for await (const chunk of req) body+=chunk; const data=JSON.parse(body); requests.push({catalog:data});
    const added=[], removed=[];
    for (const vm of state.vms) { const named=data.names.includes(vm.name); if (data.action==='add' && named && !vm.mine) { vm.mine=true; added.push(vm.name); } if (data.action==='remove' && named && vm.mine) { vm.mine=false; removed.push(vm.name); } }
    return res.end(JSON.stringify({selected:state.vms.filter(v=>v.mine).map(v=>v.name), added, removed}));
  }
  if (req.url === '/api/run') {
    let body=''; for await (const chunk of req) body+=chunk;
    if (holdRun) await new Promise(resolve=>releaseRun=resolve);
    requests.push(JSON.parse(body)); res.statusCode=failRun ? 400 : 200;
    if (!failRun) { if (dynamicVmJobs && ['start','stop'].includes(requests.at(-1).args[0])) jobId='vm:'+requests.at(-1).args[1]; jobStatus='running'; jobCommand='vmctl '+requests.at(-1).args.join(' '); }
    return res.end(JSON.stringify(failRun ? {error:'Fixture rejected the command'} : {job:jobId,command:jobCommand}));
  }
  res.statusCode=404; res.end('{}');
});
await new Promise((resolve) => server.listen(0,'127.0.0.1',resolve));
let browser;
try {
  browser = await chromium.launch({headless:true, executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined});
  const context = await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
  await context.route('https://cdn.jsdelivr.net/npm/@novnc/**', route => route.fulfill({contentType:'text/javascript',body:`export default class RFB extends EventTarget { constructor(el) { super(); el.innerHTML='<div class="console-empty">Fixture guest display</div>'; setTimeout(()=>this.dispatchEvent(new Event('connect')),20); } disconnect() {} focus() {} sendCtrlAltDel() { window.sentCAD=true; } }`}));
  if (!process.env.REAL_TERMINAL_ASSETS) await context.route('https://cdn.jsdelivr.net/npm/@xterm/**', route => {
    const url=route.request().url();
    const body=url.endsWith('.css') ? '.xterm {height:100%}' : url.includes('addon-fit') ? 'window.FitAddon={FitAddon:class { fit() {} }};' : `window.Terminal=class { constructor(){this.cols=100;this.rows=30;} loadAddon(){} open(el){this.el=el;el.textContent='Fixture SSH terminal';this.buffer={active:{length:1,getLine:()=>({translateToString:()=>this.el.textContent})}};} onData(fn){this.data=fn;} onResize(fn){this.resize=fn;} write(data){this.el.textContent+=typeof data==='string'?data:new TextDecoder().decode(data);} input(data){this.data(data);} focus(){} dispose(){} };`;
    return route.fulfill({contentType:url.endsWith('.css')?'text/css':'text/javascript',body});
  });
  const page = await context.newPage(), errors=[];
  const terminalMessages=[];
  let sshSocket;
  await page.routeWebSocket(/\/api\/vm\/.*\/ssh\?/, ws=>{sshSocket=ws;ws.onMessage(message=>{const value=JSON.parse(message);terminalMessages.push(value); if(value.type==='input') { if(value.data==='\x04' || value.data==='exit\r') ws.close({code:1000,reason:'SSH session ended'}); else ws.send('fixture-user'); }});});
  page.on('pageerror', e=>errors.push(e.message));
  const check = (label) => console.log('PASS',label);
  const shot = async (name) => page.screenshot({path:root+'artifacts/webui-review/'+name+'.png',fullPage:true});
  mkdirSync(root+'artifacts/webui-review',{recursive:true});
  await page.goto(`http://127.0.0.1:${server.address().port}/?token=fixture`);
  await page.locator('#rows [data-vm]').first().waitFor();
  assert.equal(await page.locator('#running-count').textContent(),'1');
  assert.equal(await page.locator('#details .name').textContent(),'arch-noctalia');
  await shot('dashboard'); check('dashboard and profile');
  await page.locator('#rows [data-vm="arch-noctalia"] .catalog-icon').hover();
  await page.locator('#hover-shot .hover-loading').waitFor({state:'visible'});
  assert(!(await page.locator('#hover-shot img').isVisible()));
  await shot('preview-loading');
  await page.waitForFunction(()=>document.getElementById('hover-status').textContent==='Live');
  screenDelay=0;
  assert(!(await page.locator('#hover-shot .hover-loading').isVisible()));
  assert(await page.locator('#hover-shot img').isVisible());
  await page.waitForResponse(response=>response.url().includes('/screen.png?'));
  assert(screenRequests>=2); await shot('live-preview');
  failScreen=true; await page.waitForFunction(()=>document.getElementById('hover-status').textContent==='Reconnecting');
  assert(await page.locator('#hover-shot img').isVisible());
  assert(!(await page.locator('#hover-shot .hover-loading').isVisible()));
  failScreen=false; await page.waitForFunction(()=>document.getElementById('hover-status').textContent==='Live');
  await page.locator('body > header h1').hover();
  const stoppedAt=screenRequests; await page.waitForTimeout(1200);
  assert.equal(screenRequests,stoppedAt); assert(!(await page.locator('#hover-shot').isVisible()));
  check('screen preview refreshes, reports disconnection, recovers and stops on mouse leave');
  const network=page.locator('#rows [data-vm="arch-noctalia"] .link-handle');
  await network.hover(); await page.waitForTimeout(600);
  assert(!(await page.locator('#hover-shot').isVisible()));
  await network.evaluate(el=>{
    window.stationaryNetwork=el; window.networkEnters=0;
    el.addEventListener('pointerenter',()=>window.networkEnters++);
  });
  // Both polls, other row changes and this VM's badge updates preserve the hovered handle.
  state.vms[1].label='Changed description';
  await page.evaluate(async()=>{
    await refresh(true); await refreshJobs(); await refresh(true);
    vmJobs.set('arch-noctalia',{status:'running',command:'stop'}); render();
  });
  assert(await network.evaluate(el=>el===window.stationaryNetwork && el.matches(':hover')));
  assert.equal(await page.evaluate(()=>window.networkEnters),0);
  await page.evaluate(()=>{vmJobs.clear(); render();});
  await page.waitForTimeout(5500); // Cross a real periodic state refresh without moving the mouse.
  assert(await network.evaluate(el=>el===window.stationaryNetwork && el.matches(':hover')));
  assert.equal(await page.evaluate(()=>window.networkEnters),0);
  assert(!(await page.locator('#hover-shot').isVisible()));
  state.vms[1].label='Arch Linux + Noctalia 5';
  check('stationary network handle and tooltip survive state/job polling and unrelated VM changes without hover re-entry');
  await network.focus(); await page.keyboard.press('Enter');
  assert(await page.locator('#link-dialog').isVisible());
  await page.locator('#link-target').selectOption('debian-server');
  await page.locator('#link-review').click();
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl link arch-noctalia debian-server');
  await page.locator('#confirm-no').click();
  assert.equal(requests.length,0);
  const startHandle=await network.boundingBox(), targetIcon=await page.locator('#rows [data-vm="debian-server"] .catalog-icon').boundingBox();
  await page.mouse.move(startHandle.x+10,startHandle.y+10); await page.mouse.down();
  await page.mouse.move(targetIcon.x+10,targetIcon.y+10,{steps:8});
  await page.waitForTimeout(600);
  assert(!(await page.locator('#hover-shot').isVisible()));
  await page.evaluate(()=>refresh());
  assert(await page.locator('#rows [data-vm="debian-server"]').evaluate(el=>el.classList.contains('drop-target')));
  await page.mouse.up();
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl link arch-noctalia debian-server');
  await page.locator('#confirm-no').click();
  await network.hover(); await page.mouse.down(); await page.mouse.move(targetIcon.x+10,targetIcon.y+10,{steps:8});
  await page.keyboard.press('Escape'); await page.mouse.up();
  assert(!(await page.locator('#drag-ghost').count()));
  assert.equal(requests.length,0);
  check('network picker supports keyboard; dedicated drag survives polling, suppresses preview and cancels with Escape');
  const states = await page.evaluate(() => {
    const base = S.vms[0];
    return ['start','stop','bootstrap-archinstall','fetch-iso','show'].map(job_command => stateOf({...base,job_status:'running',job_command})[0]);
  });
  assert.deepEqual(states,['Starting','Stopping','Installing','Downloading ISO','Working']);
  assert.equal(await page.evaluate(()=>stateOf({...S.vms[0],job_status:'failed (1)',job_command:'show'})[0]),'Running');
  assert(await page.evaluate(()=>actionsFor({...S.vms[0],job_status:'running',job_command:'stop'}).every(a=>!a.label.includes('Installation'))));
  check('start and stop jobs are never mislabeled as installations');
  await page.locator('#ssh-open').click();
  await page.locator('#ssh-copy').click(); assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'bin/vmctl shell arch-noctalia');
  await page.locator('#ssh-launch').click(); await page.waitForFunction(()=>document.getElementById('ssh-result').textContent.includes('requested')); assert.equal(sshLaunches,1);
  await page.locator('#ssh-browser').click(); await page.waitForFunction(()=>document.getElementById('terminal-status').textContent==='Session open');
  await page.evaluate(()=>terminal.input('whoami\r')); await page.waitForFunction(()=>Array.from({length:terminal.buffer.active.length},(_,i)=>terminal.buffer.active.getLine(i)?.translateToString()).join(' ').includes('fixture-user'));
  assert(terminalMessages.some(m=>m.type==='input'&&m.data==='whoami\r')); assert(terminalMessages.some(m=>m.type==='resize'));
  await shot('ssh-browser');
  await page.evaluate(()=>terminal.input('\x04'));
  await page.waitForFunction(()=>!document.getElementById('terminal-dialog').open);
  assert(await page.evaluate(()=>terminal===null && terminalSocket===null));
  await page.evaluate(()=>openBrowserSsh('arch-noctalia'));
  await page.waitForFunction(()=>document.getElementById('terminal-status').textContent==='Session open');
  sshSocket.send('Permission denied'); sshSocket.close({code:1011,reason:'SSH exited with status 255'});
  await page.waitForFunction(()=>document.getElementById('terminal-status').textContent==='Disconnected');
  assert(await page.locator('#terminal-dialog').evaluate(el=>el.open));
  await page.locator('#terminal-reconnect').click();
  await page.waitForFunction(()=>document.getElementById('terminal-status').textContent==='Session open');
  await page.locator('#terminal-full').click();
  await page.waitForFunction(()=>document.fullscreenElement?.id==='terminal-shell');
  await page.evaluate(()=>terminal.input('exit\r'));
  await page.waitForFunction(()=>!document.getElementById('terminal-dialog').open && !document.fullscreenElement);
  check('SSH logout closes the terminal, including full screen; connection errors stay open with reconnect');
  await page.locator('#rows [data-vm="arch-noctalia"]').click({button:'right'});
  assert(await page.locator('#vm-context').isVisible());
  const stopMenuItem=page.locator('#vm-context').getByRole('menuitem',{name:'Stop',exact:true});
  await stopMenuItem.hover();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('#vm-context button.warn:hover')).backgroundColor==='rgb(67, 57, 37)');
  await stopMenuItem.focus(); await page.keyboard.press('ArrowUp'); await page.keyboard.press('ArrowDown');
  assert(await stopMenuItem.evaluate(el=>el.matches(':focus-visible')));
  assert.equal(await stopMenuItem.evaluate(el=>getComputedStyle(el).outlineStyle),'solid');
  check('warning menu actions highlight on hover and have a visible keyboard focus');
  await page.locator('#vm-context').getByRole('menuitem',{name:'Customize profile…'}).click();
  await page.locator('#profile-memory:not([disabled])').waitFor();
  await page.locator('#profile-memory').fill('12288'); await page.locator('#profile-cpus').fill('6');
  await page.locator('#profile-save').click(); await page.waitForFunction(()=>document.getElementById('profile-feedback').textContent.startsWith('Saved locally'));
  assert.deepEqual(savedOverride,{memory_mb:12288,cpus:6});
  await page.locator('#profile-advanced summary').click(); await page.locator('#profile-json').fill('{oops'); assert(await page.locator('#profile-save').isDisabled());
  await page.locator('#profile-json').fill('{"memory_mb":12288,"cpus":6,"audio":false}'); assert(!(await page.locator('#profile-save').isDisabled()));
  await page.locator('#profile-save').click(); await page.waitForFunction(()=>document.getElementById('profile-feedback').textContent.startsWith('Saved locally')); assert.equal(savedOverride.audio,false);
  await shot('profile-editor'); await page.locator('#profile-reset').click(); await page.locator('#profile-save').click(); await page.waitForFunction(()=>document.getElementById('profile-feedback').textContent.startsWith('Saved locally')); assert.deepEqual(savedOverride,{});
  await page.locator('#profile-dialog [data-close]').click(); check('context menu, resource overrides, JSON validation, save and reset');
  await page.locator('.install-details summary').click();
  await page.evaluate(()=>render());
  assert.equal(await page.locator('.install-details').getAttribute('open'),''); check('polling preserves expanded profile');
  await page.locator('[data-filter=labs]').click();
  assert.equal(await page.locator('.lab').first().locator('.buttons button').first().textContent(),'Start stack');
  assert.equal(await page.locator('.lab').nth(1).locator('.buttons button').first().textContent(),'Install lab…');
  await shot('labs'); check('installed and new labs have different primary actions');
  await page.evaluate(() => document.addEventListener('contextmenu', e => window.labContextPrevented = e.defaultPrevented, {once:true}));
  await page.locator('[data-member="proxmox-ve-node2"] .member-address').click({button:'right'});
  assert(await page.evaluate(()=>window.labContextPrevented));
  assert.equal(await page.locator('#vm-context .context-title').textContent(),'proxmox-ve-node2');
  assert(await page.locator('#labs-view').isVisible());
  assert(await page.locator('#vm-context').getByRole('menuitem',{name:'Boot headless',exact:true}).isVisible());
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.member),'proxmox-ve-node2');
  await page.locator('[data-member="proxmox-ve-node2"]').press('Shift+F10');
  await page.locator('#vm-context').getByRole('menuitem',{name:'SSH console…'}).click();
  assert.equal(await page.locator('#ssh-title').textContent(),'SSH · proxmox-ve-node2');
  await page.locator('#ssh-dialog [data-close]').click();
  await page.locator('#labs-view [data-vm="proxmox-ve"] .state').click({button:'right'});
  assert.equal(await page.locator('#vm-context .context-title').textContent(),'proxmox-ve');
  await page.locator('#vm-context').getByRole('menuitem',{name:'All commands for proxmox-ve…',exact:true}).click();
  assert((await page.locator('#cmd-count').textContent()).endsWith('proxmox-ve'));
  await page.locator('#cmd-dialog [data-close]').click();
  assert.equal(requests.length,0);
  check('lab VM context menu handles names, addresses, status and keyboard, targeting the correct VM');
  await page.locator('[data-lab="proxmox-lab"] .lab-head').click({button:'right'});
  assert.equal(await page.locator('#vm-context').getAttribute('aria-label'),'Stack actions');
  assert.equal(await page.locator('#vm-context .context-title').textContent(),'proxmox-lab');
  assert.equal(await page.locator('#vm-context [role=menuitem]').last().textContent(),'Clean lab…');
  await page.locator('#vm-context').getByRole('menuitem',{name:'Clean lab…',exact:true}).hover();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('#vm-context button.danger:hover')).backgroundColor==='rgb(71, 44, 57)');
  await shot('stack-actions');
  await page.locator('#vm-context').getByRole('menuitem',{name:'Clean lab…',exact:true}).click();
  await page.locator('#confirm-no').click(); assert.equal(requests.length,0);
  await page.locator('[data-lab="proxmox-lab"] .lab-head').press('Shift+F10');
  await page.locator('#vm-context').getByRole('menuitem',{name:'Status',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('activity-command').textContent==='vmctl group status proxmox-lab');
  assert.deepEqual(requests.at(-1).args,['group','status','proxmox-lab']);
  assert(!(await page.locator('#log-dialog').evaluate(el=>el.open)));
  requests=[];
  check('stack context menu uses stack commands, keyboard access and destructive confirmation');
  await page.locator('[data-filter=all]').click();
  await page.locator('#rows [data-vm="arch-noctalia"]').click();
  await page.locator('#all-commands').click();
  assert.equal(await page.locator('#cmd-list [data-cmd]').first().getAttribute('data-cmd'),'stop');
  await page.locator('#cmd-filter').press('Enter'); assert.equal(requests.length,0); check('search Enter does not run a command');
  await page.locator('#cmd-filter').fill('clone'); await page.locator('#arg1').fill('new-machine');
  await page.locator('#cmd-advanced summary').click(); await page.locator('#arg2').fill('2400');
  await page.locator('#cmd-filter').fill('show'); await page.locator('#cmd-filter').fill('clone');
  assert.equal(await page.locator('#arg1').inputValue(),'new-machine'); assert.equal(await page.locator('#arg2').inputValue(),'2400');
  assert.equal(await page.locator('#cmd-advanced').getAttribute('open'),''); check('drafts survive searches and command changes');
  await page.locator('#arg1').fill(''); assert(await page.locator('#cmd-run').isDisabled());
  await page.locator('#arg1').fill('new-machine'); assert(!(await page.locator('#cmd-run').isDisabled())); check('required arguments are validated');
  await page.locator('#cmd-filter').fill(''); await page.locator('#cmd-category').selectOption('Run');
  assert(await page.locator('#cmd-list [data-cmd=start]').count()); assert.equal(await page.locator('#cmd-list [data-cmd=show]').count(),0); check('category filtering');
  await page.locator('#cmd-category').selectOption(''); await page.locator('#cmd-filter').fill('flash');
  assert(await page.locator('#cmd-run').isDisabled()); assert(await page.locator('#cmd-copy').isDisabled());
  await page.locator('#arg1').fill('/dev/test'); await page.locator('#arg2').fill('/dev/wrong'); assert(await page.locator('#cmd-copy').isDisabled());
  await page.locator('#arg2').fill('/dev/test'); assert(!(await page.locator('#cmd-copy').isDisabled()));
  await page.locator('#cmd-advanced summary').click(); await page.locator('#arg5').check(); await page.locator('#arg6').check();
  assert(!(await page.locator('#arg5').isChecked())); assert(await page.locator('#arg6').isChecked());
  assert((await page.locator('#preview').textContent()).includes('--no-expand'));
  await page.locator('#cmd-filter').press('Control+Enter'); await page.locator('#confirm-no').click(); assert.equal(requests.length,0); check('flash stays in the host terminal, device confirmation and exclusive expansion flags');
  await page.locator('#cmd-filter').fill('show'); await page.locator('#cmd-copy').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'vmctl show arch-noctalia'); check('copy command');
  await page.locator('#cmd-filter').fill('does-not-exist'); assert(await page.locator('#cmd-run').isDisabled()); check('empty search');
  await page.locator('#cmd-filter').fill('checkpoint'); await page.locator('#arg0').selectOption('restore');
  assert(!(await page.locator('#cmd-warning').evaluate(el=>el.classList.contains('hidden'))));
  await page.locator('#cmd-run').click(); await page.locator('#confirm-no').click(); assert.equal(requests.length,0); check('destructive command confirmation');
  await page.locator('#cmd-filter').fill('show'); failRun=true; await page.locator('#cmd-run').click();
  await page.waitForFunction(()=>!document.getElementById('cmd-run').disabled);
  assert(await page.locator('#cmd-dialog').evaluate(el=>el.open)); check('API failure keeps command and form open');
  failRun=false; await page.locator('#cmd-run').click();
  await page.waitForFunction(()=>!document.getElementById('cmd-dialog').open);
  assert.deepEqual(requests.at(-1).args,['show','arch-noctalia']);
  assert(!(await page.locator('#cmd-dialog').evaluate(el=>el.open)));
  assert(!(await page.locator('#log-dialog').evaluate(el=>el.open)));
  assert.equal(await page.locator('#activity-status').textContent(),'Running in background');
  assert(!(await page.locator('#activity-panel').isVisible()));
  assert(!(await page.locator('#toast').textContent()).startsWith('Started in background:'));
  assert(await page.locator('#activity').evaluate(el=>!!el.closest('body > header')));
  await page.locator('#activity-toggle').click();
  const activityPanel=await page.locator('#activity-panel').boundingBox(), activityToggle=await page.locator('#activity-toggle').boundingBox();
  assert(activityPanel.y>=activityToggle.y+activityToggle.height);
  assert(activityPanel.x>0 && activityPanel.x+activityPanel.width<=1440);
  await page.screenshot({path:root+'artifacts/webui-review/activity-menu.png'});
  await page.locator('#activity-log').click(); await page.waitForFunction(()=>document.getElementById('log').textContent.includes('Fixture job output'));
  await page.locator('#log-dialog [data-close]').click();
  assert.equal(jobStatus,'running'); check('commands run without a modal; logs open on request and closing them keeps the job running');
  await page.locator('#activity-toggle').click();
  await page.locator('#activity-cancel').click(); await page.locator('#confirm-no').click(); assert.equal(cancelRequests.length,0);
  failCancel=true;
  await page.locator('#activity-toggle').click();
  await page.locator('#activity-cancel').click(); await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>document.getElementById('toast').textContent==='Fixture cancellation failed');
  assert(!(await page.locator('#activity-cancel').isDisabled()));
  failCancel=false;
  await page.locator('#job-rows [data-job-cancel]').click(); await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>document.getElementById('activity-status').textContent==='Cancelled');
  assert.equal(cancelRequests.at(-1),'/api/jobs/web%3Afixture/cancel');
  assert(!(await page.locator('#activity-cancel').isVisible()));
  assert(!(await page.locator('#log-dialog').evaluate(el=>el.open))); check('inline cancellation requires confirmation, reports failures and updates status');
  for (const command of ['start','stop']) {
    await page.evaluate(command=>run([command,'debian-server']),command);
    assert(!(await page.locator('#log-dialog').evaluate(el=>el.open)));
    jobStatus=command==='start' ? 'completed' : 'failed (1)';
    await page.evaluate(()=>refreshJobs());
    await page.waitForFunction(status=>document.getElementById('activity-status').textContent===status,command==='start' ? 'Completed' : 'failed (1)');
    assert(!(await page.locator('#activity-cancel').isVisible()));
  }
  check('start and stop report success or failure inline without opening logs');
  await page.locator('#job-rows [data-job-log]').click();
  await page.waitForFunction(()=>document.getElementById('log').textContent.includes('Fixture job output'));
  assert(!(await page.locator('#log-cancel').isVisible()));
  await page.locator('#log-dialog [data-close]').click();
  await page.evaluate(()=>run(['show','arch-noctalia']));
  cancelResult=false;
  await page.locator('#activity-toggle').click();
  await page.locator('#activity-cancel').click(); await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>document.getElementById('toast').textContent==='Job is no longer running');
  assert.equal(jobStatus,'completed'); cancelResult=true;
  check('finished jobs retain accessible logs; cancellation races do not claim success');
  await page.locator('#all-commands').click();
  const listedCommands=await page.locator('#cmd-list [data-cmd]').evaluateAll(items=>items.map(el=>el.dataset.cmd));
  assert.equal(new Set(listedCommands).size,listedCommands.length); // Recent and suggested commands do not duplicate each other.
  await page.locator('#cmd-filter').fill('start'); await page.locator('#cmd-advanced summary').click();
  await shot('commands');
  await page.locator('#cmd-dialog [data-close]').click();
  await page.locator('#details [data-action="0"]').click(); await page.waitForFunction(()=>document.getElementById('vnc-status').textContent==='Connected');
  await page.locator('#vnc-fit').click(); assert.equal(await page.locator('#vnc-fit').textContent(),'Actual size');
  await page.locator('#vnc-cad').click(); assert(await page.evaluate(()=>window.sentCAD));
  await page.locator('#vnc-reconnect').click(); await page.waitForFunction(()=>document.getElementById('vnc-status').textContent==='Connected');
  await page.locator('#vnc-full').click(); await page.waitForFunction(()=>document.fullscreenElement?.id==='console-shell');
  await page.locator('#vnc-full').click(); await page.waitForFunction(()=>!document.fullscreenElement); await shot('console'); await page.locator('#vnc-close').click(); check('console controls, reconnect and full screen');
  failState=true; await page.evaluate(()=>refresh()); assert.equal(await page.locator('#connection').textContent(),'Disconnected · retrying');
  failState=false; await page.evaluate(()=>refresh()); assert.equal(await page.locator('#connection').textContent(),'Live'); check('connection recovery');
  const initialY=(await page.locator('#profiles-view').boundingBox()).y;
  jobId='vm:arch-noctalia'; holdRun=true;
  await page.locator('#details').getByRole('button',{name:'Stop',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#rows [data-vm="arch-noctalia"] .state')?.textContent==='Stopping');
  assert(await page.locator('#rows [data-vm="arch-noctalia"] .state').evaluate(el=>el.classList.contains('busy')));
  assert(await page.locator('#details').getByRole('button',{name:'Stop',exact:true}).isDisabled());
  assert(await page.locator('#details').getByRole('button',{name:'Open console',exact:false}).isVisible());
  assert.equal((await page.locator('#profiles-view').boundingBox()).y,initialY);
  holdRun=false; releaseRun();
  await page.waitForFunction(()=>!submittingVms.has('arch-noctalia'));
  await page.evaluate(()=>refreshJobs()); await page.evaluate(()=>refresh());
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Stopping');
  assert.equal(await page.locator('#rows [data-vm="debian-server"] .state').textContent(),'Boot verified');
  await shot('vm-stopping');
  await page.locator('#rows [data-vm="arch-noctalia"] .state').click();
  await page.waitForFunction(()=>document.getElementById('log').textContent.includes('Fixture job output'));
  await page.locator('#log-dialog [data-close]').click();
  await page.locator('#details').getByRole('button',{name:'Force stop',exact:true}).click();
  assert.equal(await page.locator('#confirm-title').textContent(),'Force stop this VM?');
  await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>!S.vms[0].running && vmJobs.get('arch-noctalia')?.status==='cancelled');
  assert.equal(cancelRequests.at(-1),'/api/jobs/vm%3Aarch-noctalia/cancel');
  assert(!(await page.locator('#rows [data-vm="arch-noctalia"] .state').evaluate(el=>el.classList.contains('busy'))));
  assert(await page.locator('#details').getByRole('button',{name:'Boot headless',exact:false}).isVisible());
  state.vms[0].running=true; jobId='web:fixture'; jobStatus='completed';
  await page.evaluate(()=>{ vmJobs.clear(); }); await page.evaluate(()=>refresh());
  check('row progress is immediate, survives stale snapshots, keeps controls visible and supports confirmed force stop');
  // Completion must not expose controls based on a snapshot taken before completion.
  jobId='vm:arch-noctalia';
  await page.keyboard.press('F8'); await page.waitForFunction(()=>!submittingVms.size);
  await page.evaluate(()=>refreshJobs());
  assert(await page.locator('#job-bar').isVisible());
  assert((await page.locator('#job-bar-status').textContent()).includes('Stopping'));
  await page.locator('#job-bar-log').click();
  await page.waitForFunction(()=>document.getElementById('log').textContent.includes('Fixture job output'));
  await page.locator('#log-dialog [data-close]').click();
  holdState=true; jobStatus='completed';
  await page.evaluate(()=>refreshJobs());
  await page.waitForFunction(()=>vmJobs.get('arch-noctalia')?.confirming);
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Stopping');
  assert(await page.locator('#details').getByRole('button',{name:'Stop',exact:true}).isDisabled());
  assert((await page.locator('#job-bar-status').textContent()).includes('Checking'));
  await shot('job-bar-confirming');
  await page.locator('#job-bar-cancel').click();
  assert.equal(await page.locator('#confirm-title').textContent(),'Force stop this VM?');
  await page.locator('#confirm-no').click();
  state.vms[0].running=false; holdState=false; stateWaiters.splice(0).forEach(resolve=>resolve());
  await page.waitForFunction(()=>stateRefresh===null);
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Stopping');
  await page.evaluate(()=>refresh(true));
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Stopped');
  assert(!(await page.locator('#job-bar').isVisible()));
  await page.keyboard.press('F2'); await page.waitForFunction(()=>!submittingVms.size);
  jobStatus='completed'; failState=true;
  await page.evaluate(()=>refreshJobs()); await page.waitForFunction(()=>stateRefresh===null);
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Starting');
  assert(await page.locator('#job-bar').isVisible());
  failState=false; state.vms[0].running=true; await page.evaluate(()=>refresh(true));
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Running');
  assert(!(await page.locator('#job-bar').isVisible()));
  // A successful command with an unexpected state must eventually explain the mismatch.
  await page.keyboard.press('F8'); await page.waitForFunction(()=>!submittingVms.size);
  jobStatus='completed'; await page.evaluate(()=>refreshJobs()); await page.waitForFunction(()=>stateRefresh===null);
  await page.evaluate(()=>{vmJobs.get('arch-noctalia').finishedAt=Date.now()-31000;});
  await page.evaluate(()=>refresh(true));
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Still running');
  assert(!(await page.locator('#job-bar').isVisible()));
  await page.evaluate(()=>refreshJobs());
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] .state').textContent(),'Still running');
  check('F2/F8 retain transitions through stale snapshots and connection failures; completion hides the job bar and unexpected states are explicit');
  await page.evaluate(()=>{vmJobs.clear();});
  await page.keyboard.press('F8'); await page.waitForFunction(()=>!submittingVms.size);
  await page.locator('#job-bar-cancel').click(); await page.locator('#confirm-no').click();
  const beforeCancel=cancelRequests.length;
  await page.locator('#job-bar-cancel').click(); await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>!document.getElementById('job-bar').offsetHeight);
  assert.equal(cancelRequests.length,beforeCancel+1);
  state.vms[0].running=true; jobStatus='completed'; jobId='web:fixture';
  await page.evaluate(()=>{vmJobs.clear();}); await page.evaluate(()=>refresh());
  check('bottom job bar opens logs, confirms cancellation and disappears when the job ends');
  const row=name=>page.locator(`#rows [data-vm="${name}"] .profile-name`);
  await row('arch-noctalia').click();
  await row('debian-server').click({modifiers:['Control']});
  assert.equal(await page.locator('#selection-count').textContent(),'2 selected');
  await row('proxmox-ve').click({modifiers:['Shift']});
  assert.deepEqual(await page.evaluate(()=>[...checkedVms]),['debian-server','proxmox-ve']);
  await row('arch-noctalia').click({modifiers:['Meta']});
  assert.equal(await page.locator('#selection-count').textContent(),'3 selected');
  await page.evaluate(()=>refresh());
  assert.equal(await page.locator('#rows .vm-select[aria-pressed="true"]').count(),3);
  assert.equal(await page.locator('#rows input[type=checkbox]').count(),0);
  await row('debian-server').click({button:'right'});
  assert.equal(await page.locator('#vm-context .context-title').textContent(),'3 machines selected');
  assert.equal(await page.locator('#vm-context').getAttribute('aria-label'),'Selected machines actions');
  assert((await page.locator('#vm-context .context-selection').textContent()).includes('arch-noctalia'));
  assert.equal(await page.locator('#vm-context').getByRole('menuitem',{name:'Customize profile…'}).count(),0);
  await page.screenshot({path:root+'artifacts/webui-review/selection-context.png'});
  await page.locator('#vm-context').getByRole('menuitem',{name:'Link selected on a network (3)',exact:true}).click();
  const countBeforeLink=requests.length;
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl link arch-noctalia debian-server proxmox-ve');
  await page.locator('#confirm-no').click(); assert.equal(requests.length,countBeforeLink);
  await page.locator('#rows [data-vm="arch-noctalia"]').press('Shift+F10');
  assert.equal(await page.locator('#vm-context .context-title').textContent(),'3 machines selected');
  await page.locator('#vm-context').getByRole('menuitem',{name:'Link selected on a network (3)',exact:true}).click();
  await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>!bulkBusy);
  assert.deepEqual(requests.at(-1).args,['link','arch-noctalia','debian-server','proxmox-ve']);
  jobStatus='completed'; await page.evaluate(()=>refreshJobs());
  // Existing links replace the network action, even in an already open context menu.
  await row('arch-noctalia').click({button:'right'});
  const linkRecord=segment=>({segment,address:'192.168.100.1/24',up:false,peers:[]});
  for (const vm of state.vms.slice(0,4)) vm.links=[linkRecord('session')];
  await page.evaluate(()=>refresh(true));
  assert.equal(await page.locator('#selection-link').textContent(),'Unlink network (3)');
  const unlinkMenu=page.locator('#vm-context').getByRole('menuitem',{name:'Unlink selected from network (3)',exact:true});
  assert(await unlinkMenu.isVisible());
  await unlinkMenu.click();
  const unlinkBefore=requests.length;
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl link --off --segment session arch-noctalia debian-server proxmox-ve');
  assert((await page.locator('#confirm-message').textContent()).includes('Other members stay connected'));
  await page.locator('#confirm-no').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.equal(requests.length,unlinkBefore);
  await page.locator('#selection-link').click();
  // A changed membership while reviewing must abort instead of unlinking stale targets.
  state.vms[2].links=[]; await page.evaluate(()=>refresh(true));
  await page.locator('#confirm-yes').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.equal(requests.length,unlinkBefore);
  assert.equal(await page.locator('#selection-link').textContent(),'Link network (3)');
  for (const vm of state.vms.slice(0,3)) vm.links=[linkRecord('session'),linkRecord('backend')];
  await page.evaluate(()=>refresh(true));
  await page.locator('#selection-link').click();
  assert(await page.locator('#unlink-dialog').isVisible());
  await page.locator('#unlink-segment').selectOption('backend');
  await page.locator('#unlink-review').click();
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl link --off --segment backend arch-noctalia debian-server proxmox-ve');
  await page.locator('#confirm-yes').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.deepEqual(requests.at(-1).args,['link','--off','--segment','backend','arch-noctalia','debian-server','proxmox-ve']);
  assert(!requests.at(-1).args.includes('proxmox-ve-node2'));
  for (const vm of state.vms.slice(0,3)) vm.links=[];
  jobStatus='completed'; await page.evaluate(()=>refreshJobs()); await page.evaluate(()=>refresh(true));
  assert.equal(await page.locator('#selection-link').textContent(),'Link network (3)');
  state.vms[3].links=[];
  // Drag uses the same existing-network decision, and only acts on the dragged pair.
  for (const vm of state.vms.slice(0,4)) vm.links=[linkRecord('session')];
  await page.evaluate(()=>refresh(true));
  const dragPair=async()=>{
    const from=await page.locator('#rows [data-vm="arch-noctalia"] .link-handle').boundingBox();
    const to=await page.locator('#rows [data-vm="debian-server"] .catalog-icon').boundingBox();
    await page.mouse.move(from.x+10,from.y+10); await page.mouse.down();
    await page.mouse.move(to.x+10,to.y+10,{steps:8}); await page.mouse.up();
  };
  const beforePair=requests.length;
  await dragPair();
  assert.equal(await page.locator('#confirm-title').textContent(),'Unlink 2 machines?');
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl link --off --segment session arch-noctalia debian-server');
  await page.locator('#confirm-no').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.equal(requests.length,beforePair);
  await dragPair(); await page.locator('#confirm-yes').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.deepEqual(requests.at(-1).args,['link','--off','--segment','session','arch-noctalia','debian-server']);
  assert.equal(await page.evaluate(()=>checkedVms.size),3);
  jobStatus='completed'; await page.evaluate(()=>refreshJobs());
  for (const vm of state.vms.slice(0,2)) vm.links.push(linkRecord('backend'));
  await page.evaluate(()=>refresh(true));
  await page.locator('#rows [data-vm="arch-noctalia"] .link-handle').click();
  await page.locator('#link-target').selectOption('debian-server');
  assert.equal(await page.locator('#link-review').textContent(),'Review unlink…');
  await page.locator('#link-review').click();
  assert(await page.locator('#unlink-dialog').isVisible());
  assert.equal(await page.locator('#unlink-members').textContent(),'arch-noctalia · debian-server');
  await page.locator('#unlink-segment').selectOption('backend');
  await page.locator('#unlink-review').click();
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl link --off --segment backend arch-noctalia debian-server');
  await page.locator('#confirm-yes').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.deepEqual(requests.at(-1).args,['link','--off','--segment','backend','arch-noctalia','debian-server']);
  for (const vm of state.vms.slice(0,4)) vm.links=[];
  jobStatus='completed'; await page.evaluate(()=>refreshJobs()); await page.evaluate(()=>refresh(true));
  check('drag and picker offer unlink for existing peers, preserve the wider selection and disconnect only the pair on the chosen network');
  check('shared links offer unlink in toolbar and live context menu; cancellation, stale membership, multiple segments and explicit VM scope are handled');
  state.vms[1].running=true; await page.evaluate(()=>refresh(true));
  dynamicVmJobs=true;
  await row('arch-noctalia').click({button:'right'});
  await page.locator('#vm-context').getByRole('menuitem',{name:'Stop selected (2)',exact:true}).click();
  assert.equal(await page.locator('#confirm-command').textContent(),'vmctl stop arch-noctalia\nvmctl stop debian-server');
  assert((await page.locator('#confirm-message').textContent()).includes('1 selected machine(s)'));
  const countBeforeStop=requests.length;
  await page.locator('#confirm-yes').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.deepEqual(requests.slice(countBeforeStop).map(r=>r.args),[['stop','arch-noctalia'],['stop','debian-server']]);
  await shot('multi-selection');
  await page.setViewportSize({width:390,height:844});
  const mobileBar=await page.locator('#job-bar').boundingBox();
  assert(mobileBar.x>=0 && mobileBar.x+mobileBar.width<=390 && mobileBar.y+mobileBar.height<=844);
  assert(await page.locator('#job-bar-cancel').isVisible());
  await shot('multi-selection-mobile');
  await page.setViewportSize({width:1440,height:1000});
  // Starting a selected group submits only stopped, eligible machines.
  await page.evaluate(()=>{vmJobs.clear();});
  state.vms[0].running=false; state.vms[1].running=false;
  await page.evaluate(()=>refresh(true));
  // F2/F8 act on the selection, through the same confirmation as the toolbar.
  await page.evaluate(()=>document.activeElement?.blur());
  await page.keyboard.press('F2');
  assert.equal(await page.locator('#confirm-title').textContent(),'Start 3 machines?');
  assert.match(await page.locator('#confirm-command').textContent(),/vmctl start debian-server --headless --background/);
  await page.locator('#confirm-no').click();
  const countBeforeF8=requests.length;
  await page.evaluate(()=>document.activeElement?.blur());
  await page.keyboard.press('F8');  // nothing selected is running: a notice, no dialog, no request
  assert(!(await page.locator('#confirm-dialog').isVisible()));
  assert.equal(requests.length,countBeforeF8);
  await page.locator('#selection-start').click();
  const countBeforeStart=requests.length;
  await page.locator('#confirm-yes').click(); await page.waitForFunction(()=>!bulkBusy);
  assert.deepEqual(requests.slice(countBeforeStart).map(r=>r.args),[
    ['start','arch-noctalia','--headless','--background'],
    ['start','debian-server','--headless','--background'],
    ['start','proxmox-ve','--headless','--background']]);
  state.vms[0].running=true;
  await page.locator('#search').fill('arch');
  assert(!(await page.locator('#selection-bar').isVisible()));
  await page.locator('#search').fill('');
  await page.evaluate(()=>{vmJobs.clear(); knownJobs=[]; activityJob=null;});
  state.vms[1].running=false; jobId='web:fixture'; jobStatus='completed'; dynamicVmJobs=false;
  await page.evaluate(()=>refresh()); await page.evaluate(()=>refreshJobs());
  await row('arch-noctalia').click();
  await page.locator('#rows [data-vm="arch-noctalia"] .vm-select').click();
  await page.locator('#rows [data-vm="debian-server"] .vm-select').focus(); await page.keyboard.press('Space');
  assert.equal(await page.locator('#rows .vm-select[aria-pressed="true"]').count(),2);
  await page.evaluate(()=>refresh());
  assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Deselect debian-server');
  await row('proxmox-ve-node2').click({button:'right'});
  assert.equal(await page.locator('#vm-context .context-title').textContent(),'proxmox-ve-node2');
  assert.equal(await page.evaluate(()=>checkedVms.size),0);
  await page.keyboard.press('Escape'); await row('arch-noctalia').click();
  check('icon selection and Ctrl/Cmd/Shift work without checkboxes; F2/F8 start/stop the selection; mouse and keyboard context menus target the selection, outside clicks reset the scope');
  assert.equal(await page.locator('#rows [data-vm="arch-noctalia"] use').getAttribute('href'),'/assets/distro-icons.svg#arch');
  assert.equal(await page.locator('.catalog-icon text').count(),0);
  check('distribution icons use the local SVG sprite, without monogram placeholders');
  for (const width of [1440,1100,909,768,720,390]) {
    await page.setViewportSize({width,height:900});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert(await page.locator('#list').evaluate(el=>el.scrollWidth<=el.clientWidth));
    const primary = await page.locator('#details .main-action').boundingBox();
    if (width>720) assert(primary.y+primary.height<700);
    await shot('dashboard-'+width);
    await page.locator('#all-commands').click();
    await page.locator('#cmd-filter').fill('start');
    const dialog=await page.locator('#cmd-dialog').boundingBox(), run=await page.locator('#cmd-run').boundingBox();
    assert(run.y+run.height<=dialog.y+dialog.height); assert(run.x+run.width<=width);
    assert(await page.locator('#cmd-dialog').evaluate(el=>el.scrollHeight<=el.clientHeight));
    await shot('commands-'+width); await page.locator('#cmd-dialog [data-close]').click();
  }
  check('six viewport sizes keep profiles, primary actions and execution footer within bounds');
  await page.evaluate(()=>{activityJob={id:'web:fixture',command:'vmctl show arch-noctalia',status:'completed'};renderActivity();});
  await page.locator('#activity-toggle').click();
  await page.locator('#activity-dismiss').click(); assert(!(await page.locator('#activity').isVisible()));
  assert(await page.locator('#job-rows [data-job-log]').isVisible());
  check('completed activity can be dismissed while its log remains available');
  // My VMs: nothing chosen opens on All; choosing from the context menu stars the row, the filter
  // shows the choice plus whatever runs, the details button and the selection bar toggle it.
  assert.equal(await page.locator('[data-filter].active').getAttribute('data-filter'),'all');
  assert.equal(await page.locator('#rows .mine-mark').count(),0);
  await row('debian-server').click({button:'right'});
  await page.locator('#vm-context button', {hasText:'Add to My VMs'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#rows .mine-mark').length===1);
  assert.deepEqual(requests.at(-1),{catalog:{action:'add',names:['debian-server']}});
  await page.locator('[data-filter="mine"]').click();
  assert.deepEqual(await page.locator('#rows [data-vm]').evaluateAll(rows=>rows.map(r=>r.dataset.vm)),['arch-noctalia','debian-server']);
  assert.match(await page.locator('#list-title').textContent(),/^My VMs/);
  await row('debian-server').click();
  assert.equal(await page.locator('#profile-mine').textContent(),'★');
  await page.locator('#profile-mine').click();
  await page.waitForFunction(()=>document.querySelectorAll('#rows .mine-mark').length===0);
  assert.deepEqual(requests.at(-1),{catalog:{action:'remove',names:['debian-server']}});
  assert.equal(await page.locator('[data-filter].active').getAttribute('data-filter'),'all');  // an empty selection leaves My VMs
  await page.locator('#rows [data-vm="debian-server"] .vm-select').click();
  await page.locator('#rows [data-vm="proxmox-ve"] .vm-select').click();
  assert.equal(await page.locator('#selection-mine').textContent(),'Add to My VMs (2)');
  await page.locator('#selection-mine').click();
  await page.waitForFunction(()=>document.querySelectorAll('#rows .mine-mark').length===2);
  assert.deepEqual(requests.at(-1).catalog,{action:'add',names:['debian-server','proxmox-ve']});
  await page.evaluate(()=>{ for (const v of state.vms) v.mine=false; }).catch(()=>{}); state.vms.forEach(v=>v.mine=false);
  await page.locator('#selection-clear').click();
  await page.evaluate(()=>refresh(true));
  check('My VMs: context menu, filter, details button and selection bar');
  assert.deepEqual(errors,[]); check('no browser JavaScript errors');
} finally { if (browser) await browser.close(); server.closeAllConnections(); await new Promise(resolve=>server.close(resolve)); }
