"""Alpine Linux unattended install helpers: setup-alpine answer file, chroot script, seed ISO.

The flow boots the Alpine live ISO headless with serial stdio, logs in as root
automatically, mounts a small seed ISO and runs ``install.sh`` from it:

1. ``setup-alpine -e -f answers`` does the whole base install (network, apk
   mirror + community repo, user with SSH key, sshd, ``setup-disk -m sys``).
   ``ERASE_DISKS`` is exported so setup-disk never asks for confirmation.
2. The installed root is mounted back and a chroot script adds the packages of
   the profile, sets the user password and passwordless sudo, then runs the
   profile's ``chroot_commands`` (greetd config, services, ...).
3. Filesystems are unmounted, buffers flushed, the completion token printed and
   the guest powers itself off (see CLAUDE.md: flush -> token -> poweroff).
"""
from __future__ import annotations

import shlex
from pathlib import Path
from typing import Any

from vmctl import cloud_init, iso, runtime, ssh
from vmctl.errors import VMError


BOOTSTRAP_COMPLETE_TOKEN = "==> Alpine Linux installation complete!"

# Serial console prompts of the live ISO (hostname is ``localhost`` until setup-alpine runs).
ALPINE_SERIAL_LOGIN_PROMPT = "localhost login:"
ALPINE_LIVE_PROMPT = "localhost:~#"

SEED_VOLUME_ID = "ALPINESEED"
SEED_MOUNTPOINT = "/media/vmctl-seed"

# Kernel line for booting the live ISO with -kernel/-initrd: same module list as
# the ISO's syslinux.cfg, plus virtio so /dev/vdb (the seed) exists, plus serial.
LIVE_KERNEL_APPEND = (
    "modules=loop,squashfs,sd-mod,usb-storage,virtio_blk,virtio_pci "
    "console=tty0 console=ttyS0,115200 quiet"
)

# What the profile can rely on without listing it: the compositor itself plus
# the seat/dbus plumbing and sudo for post-install.
DEFAULT_PACKAGES = ["sudo", "bash", "dbus", "dbus-openrc", "seatd", "seatd-openrc", "eudev"]


def alpine_config(vm: dict[str, Any]) -> dict[str, Any] | None:
    cfg = vm.get("alpine_config")
    if cfg is None:
        return None
    if not isinstance(cfg, dict):
        raise VMError("Invalid alpine_config: expected object")
    return cfg


def alpine_artifact_dir(vm: dict[str, Any]) -> Path:
    return runtime.resolve_path(vm["disk"]["path"]).parent / "alpine"


def _resolve_ssh_pubkey(vm: dict[str, Any]) -> str | None:
    ssh_cfg = vm.get("ssh_provision")
    if not isinstance(ssh_cfg, dict):
        return None
    pubkey = ssh.resolve_ssh_public_key(vm, ssh_cfg)
    if pubkey is None:
        return None
    return pubkey.read_text(encoding="utf-8").strip()


def _require_identity(cfg: dict[str, Any]) -> tuple[str, str]:
    username = str(cfg.get("username") or "").strip()
    password_hash = str(cfg.get("password_hash") or "").strip()
    if not username:
        raise VMError("alpine_config.username is required")
    if not password_hash:
        raise VMError("alpine_config.password_hash is required (openssl passwd -6)")
    return username, password_hash


def _sh_dq(value: str) -> str:
    """Escape *value* for use inside a double-quoted POSIX sh string."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")


def render_answerfile(vm_name: str, vm: dict[str, Any]) -> str:
    """Render the file consumed by ``setup-alpine -f`` (it is sourced by sh)."""
    cfg = alpine_config(vm)
    if cfg is None:
        raise VMError("VM profile does not define alpine_config")
    username, _ = _require_identity(cfg)

    hostname = str(cfg.get("hostname") or vm_name).strip()
    timezone = str(cfg.get("timezone") or "UTC").strip()
    kb_layout = str(cfg.get("keyboard_layout") or "us").strip()
    kb_variant = str(cfg.get("keyboard_variant") or kb_layout).strip()
    disk_device = str(cfg.get("disk_device") or "vda").strip()
    ntp = str(cfg.get("ntp") or "chrony").strip()
    groups = ",".join(cfg.get("user_groups") or ["audio", "input", "video", "netdev"])

    lines = [
        f"# setup-alpine answer file generated by vmctl for {vm_name}",
        f'KEYMAPOPTS="{_sh_dq(kb_layout)} {_sh_dq(kb_variant)}"',
        f'HOSTNAMEOPTS="{_sh_dq(hostname)}"',
        # udev instead of mdev: needed for input devices and GPU nodes under a compositor
        "DEVDOPTS=udev",
        'INTERFACESOPTS="auto lo',
        "iface lo inet loopback",
        "",
        "auto eth0",
        "iface eth0 inet dhcp",
        f"    hostname {_sh_dq(hostname)}",
        '"',
        "DNSOPTS=none",
        f'TIMEZONEOPTS="{_sh_dq(timezone)}"',
        "PROXYOPTS=none",
        # first mirror of the list + community repository
        'APKREPOSOPTS="-1 -c"',
        # admin user (wheel + doas), unlocked, no interactive password prompt
        f'USEROPTS="-a -u -g {_sh_dq(groups)} {_sh_dq(username)}"',
    ]
    pubkey = _resolve_ssh_pubkey(vm)
    if pubkey:
        lines.append(f'USERSSHKEY="{_sh_dq(pubkey)}"')
    lines += [
        "SSHDOPTS=openssh",
        f'NTPOPTS="{_sh_dq(ntp)}"',
        f'DISKOPTS="-m sys /dev/{_sh_dq(disk_device)}"',
        "LBUOPTS=none",
        "APKCACHEOPTS=none",
    ]
    return "\n".join(lines) + "\n"


def render_install_script(vm_name: str, vm: dict[str, Any]) -> str:
    """Render ``install.sh``: runs in the live environment as root, busybox sh."""
    cfg = alpine_config(vm)
    if cfg is None:
        raise VMError("VM profile does not define alpine_config")
    username, password_hash = _require_identity(cfg)

    disk_device = str(cfg.get("disk_device") or "vda").strip()
    packages: list[str] = list(DEFAULT_PACKAGES)
    for pkg in cfg.get("packages") or []:
        if pkg not in packages:
            packages.append(str(pkg))
    optional_packages: list[str] = [str(p) for p in (cfg.get("optional_packages") or [])]
    chroot_commands: list[str] = [str(c) for c in (cfg.get("chroot_commands") or [])]
    # setup-disk appends KERNELOPTS to the installed bootloader entries: keep a
    # serial console so post-install-serial.log stays useful after the install.
    kernel_opts = str(cfg.get("kernel_opts") or "quiet console=tty0 console=ttyS0,115200").strip()

    packages_str = " ".join(shlex.quote(p) for p in packages)
    optional_str = " ".join(shlex.quote(p) for p in optional_packages)
    custom_block = "\n".join(chroot_commands) if chroot_commands else "true"
    chpasswd_line = shlex.quote(f"{username}:{password_hash}")

    return f"""\
#!/bin/sh
# Alpine Linux unattended install generated by vmctl for {vm_name}
set -eu
SEED_DIR="$(dirname "$(readlink -f "$0")")"
DISK=/dev/{disk_device}
TARGET=/mnt/vmctl-target

log() {{ echo "[vmctl-alpine] $*"; }}

log "Running setup-alpine with the answer file"
export ERASE_DISKS="$DISK"
export KERNELOPTS={shlex.quote(kernel_opts)}
setup-alpine -e -f "$SEED_DIR/answers"

log "Mounting the installed system"
mkdir -p "$TARGET"
ROOT_PART=""
for part in "$DISK"3 "$DISK"2 "$DISK"4; do
    if mount -t ext4 "$part" "$TARGET" 2>/dev/null; then
        if [ -f "$TARGET/etc/alpine-release" ]; then
            ROOT_PART="$part"
            break
        fi
        umount "$TARGET"
    fi
done
if [ -z "$ROOT_PART" ]; then
    log "ERROR: installed root filesystem not found on $DISK"
    exit 1
fi
log "Root filesystem: $ROOT_PART"
mount "$DISK"1 "$TARGET/boot"
mount -t proc none "$TARGET/proc"
mount --bind /sys "$TARGET/sys"
mount --bind /dev "$TARGET/dev"
cp /etc/resolv.conf "$TARGET/etc/resolv.conf"

cat > "$TARGET/tmp/vmctl-chroot.sh" <<'CHROOT_EOF'
set -eu
log() {{ echo "[vmctl-alpine:chroot] $*"; }}

log "Installing packages"
apk update
apk add {packages_str}
for pkg in {optional_str}; do
    apk add "$pkg" || log "optional package unavailable: $pkg"
done

log "User password, groups and passwordless sudo"
echo {chpasswd_line} | chpasswd -e
addgroup {username} seat 2>/dev/null || true
mkdir -p /etc/sudoers.d
echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel
chmod 0440 /etc/sudoers.d/wheel

log "Base services"
rc-update add dbus default || true
rc-update add seatd default || true

log "Profile chroot commands"
{custom_block}
CHROOT_EOF
chroot "$TARGET" /bin/sh /tmp/vmctl-chroot.sh
rm -f "$TARGET/tmp/vmctl-chroot.sh"

log "Unmounting"
umount "$TARGET/dev" "$TARGET/sys" "$TARGET/proc" "$TARGET/boot" || true
umount "$TARGET" || true

sync
blockdev --flushbufs "$DISK" "$DISK"1 "$DISK"2 "$DISK"3 2>/dev/null || true
echo "{BOOTSTRAP_COMPLETE_TOKEN}"
poweroff -f
"""


def create_alpine_seed_iso(vm_name: str, vm: dict[str, Any], dry_run: bool = False) -> Path:
    """Pack answers + install.sh + run.sh into the seed ISO mounted by the live trigger."""
    artifact_dir = alpine_artifact_dir(vm)
    run_sh = f"#!/bin/sh\nset -eu\nexec sh {SEED_MOUNTPOINT}/install.sh\n"
    return cloud_init.create_iso_with_files(
        artifact_dir,
        {
            "answers": render_answerfile(vm_name, vm),
            "install.sh": render_install_script(vm_name, vm),
            "run.sh": run_sh,
        },
        dry_run=dry_run,
        volume_id=SEED_VOLUME_ID,
    )


def seed_iso_drive_args(iso_path: Path) -> list[str]:
    return ["-drive", f"file={iso_path},format=raw,if=virtio,media=cdrom,readonly=on"]


def live_trigger_command() -> str:
    """What run_and_expect types at the live root prompt: mount the seed, run it."""
    return (
        "modprobe virtio_blk 2>/dev/null; mdev -s 2>/dev/null; "
        f"mkdir -p {SEED_MOUNTPOINT} && mount -t iso9660 /dev/vdb {SEED_MOUNTPOINT} && sh {SEED_MOUNTPOINT}/run.sh"
    )


def extract_alpine_boot_artifacts(vm: dict[str, Any], iso_path: Path, dry_run: bool = False) -> tuple[Path, Path]:
    """Extract vmlinuz + initramfs of the ISO's kernel flavor (``lts`` for standard, ``virt`` for virt)."""
    cfg = alpine_config(vm) or {}
    flavor = str(cfg.get("kernel_flavor") or "lts").strip()
    boot = vm.get("installer_boot", {})
    kernel_member = str(boot.get("kernel") or f"boot/vmlinuz-{flavor}")
    initrd_member = str(boot.get("initrd") or f"boot/initramfs-{flavor}")
    artifact_dir = iso.installer_artifact_dir(vm)
    kernel_path = artifact_dir / "vmlinuz"
    initrd_path = artifact_dir / "initrd"
    iso.extract_iso_member(iso_path, kernel_member, kernel_path, dry_run=dry_run)
    iso.extract_iso_member(iso_path, initrd_member, initrd_path, dry_run=dry_run)
    return kernel_path, initrd_path
