"""AlmaLinux/RHEL kickstart install helpers: config generation, boot artifacts, ISO packing."""
from __future__ import annotations

import shlex
from pathlib import Path
from typing import Any

from vmctl import cloud_init, iso, runtime, ssh
from vmctl.errors import VMError


BOOTSTRAP_COMPLETE_TOKEN = "==> Kickstart install complete!"


def _resolve_ssh_pubkey(vm: dict[str, Any]) -> str | None:
    ssh_cfg = vm.get("ssh_provision")
    if not isinstance(ssh_cfg, dict):
        return None
    pubkey = ssh.resolve_ssh_public_key(vm, ssh_cfg)
    if pubkey is None:
        return None
    return pubkey.read_text(encoding="utf-8").strip()


def kickstart_config(vm: dict[str, Any]) -> dict[str, Any] | None:
    cfg = vm.get("kickstart_config")
    if cfg is None:
        return None
    if not isinstance(cfg, dict):
        raise VMError("Invalid kickstart_config: expected object")
    return cfg


def kickstart_artifact_dir(vm: dict[str, Any]) -> Path:
    return runtime.resolve_path(vm["disk"]["path"]).parent / "kickstart"


def render_kickstart(vm_name: str, vm: dict[str, Any]) -> str:
    cfg = kickstart_config(vm)
    if cfg is None:
        raise VMError("VM profile does not define kickstart_config")

    hostname = str(cfg.get("hostname") or vm_name).strip()
    username = str(cfg.get("username") or "").strip()
    fullname = str(cfg.get("fullname") or username).strip()
    password_hash = str(cfg.get("password_hash") or "").strip()
    password = str(cfg.get("password") or "").strip()
    timezone = str(cfg.get("timezone") or "UTC").strip()
    kb_layout = str(cfg.get("keyboard_layout") or "us").strip()
    locale = str(cfg.get("locale") or "en_US.UTF-8").strip()
    packages: list[str] = list(cfg.get("packages") or ["@^minimal-environment", "openssh-server", "sudo", "vim-minimal"])
    post_commands: list[str] = list(cfg.get("post_commands") or [])
    disk_device = str(cfg.get("disk_device") or "vda").strip()
    selinux = str(cfg.get("selinux") or "enforcing").strip()
    firewall = str(cfg.get("firewall") or "enabled").strip()

    if not username:
        raise VMError("kickstart_config.username is required")
    if not password_hash and not password:
        raise VMError("kickstart_config.password_hash or password is required")

    pw_directive = ""
    if password_hash:
        pw_directive = f"user --name={username} --groups=wheel --gecos=\"{fullname}\" --password=\"{password_hash}\" --iscrypted"
    else:
        pw_directive = f"user --name={username} --groups=wheel --gecos=\"{fullname}\" --password=\"{password}\" --plaintext"

    pubkey = _resolve_ssh_pubkey(vm)
    ssh_key_block = ""
    if pubkey:
        pubkey_quoted = shlex.quote(pubkey)
        ssh_key_block = f"""
echo "==> Installing SSH public key for {username}..."
install -d -m 700 -o {username} -g {username} /home/{username}/.ssh
echo {pubkey_quoted} > /home/{username}/.ssh/authorized_keys
chown {username}:{username} /home/{username}/.ssh/authorized_keys
chmod 600 /home/{username}/.ssh/authorized_keys
# Ensure SELinux context is correct for SSH keys
restorecon -R /home/{username}/.ssh
"""

    custom_commands_block = ""
    if post_commands:
        rendered_commands = "\n".join(post_commands)
        custom_commands_block = f"""
log "Kickstart post customization..."
{rendered_commands}
"""

    packages_str = "\n".join(packages)
    
    # We use poweroff instead of reboot to let run_and_expect notice it
    return f"""\
# AlmaLinux/RHEL kickstart generated by vmctl
lang {locale}
keyboard {kb_layout}
timezone {timezone} --utc

network --bootproto=dhcp --hostname={hostname}
firewall --{firewall}
selinux --{selinux}

rootpw --lock
{pw_directive}

clearpart --all --initlabel --drives={disk_device}
autopart --type=plain --noswap

bootloader --append="crashkernel=auto"
skipx
text
poweroff

%packages
{packages_str}
%end

%post --erroronfail
log() {{
    echo "[kickstart-post] $*" > /dev/console 2>&1 || true
    echo "[kickstart-post] $*" > /dev/ttyS0 2>&1 || true
    echo "[kickstart-post] $*"
}}

{ssh_key_block}

log "Sudoers setup..."
echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/nopasswd-wheel
chmod 0440 /etc/sudoers.d/nopasswd-wheel

{custom_commands_block}

log "Syncing and flushing buffers..."
sync
blockdev --flushbufs /dev/{disk_device} /dev/{disk_device}1 /dev/{disk_device}2 || true
echo "{BOOTSTRAP_COMPLETE_TOKEN}" > /dev/console 2>&1 || true
echo "{BOOTSTRAP_COMPLETE_TOKEN}" > /dev/ttyS0 2>&1 || true
echo "{BOOTSTRAP_COMPLETE_TOKEN}"
%end
"""


def extract_kickstart_boot_artifacts(vm: dict[str, Any], iso_path: Path, dry_run: bool = False) -> tuple[Path, Path]:
    artifact_dir = kickstart_artifact_dir(vm)
    kernel_path = artifact_dir / "vmlinuz"
    initrd_path = artifact_dir / "initrd"
    boot = vm.get("installer_boot", {})
    kernel_member = str(boot.get("kernel") or "images/pxeboot/vmlinuz")
    initrd_member = str(boot.get("initrd") or "images/pxeboot/initrd.img")
    iso.extract_iso_member(iso_path, kernel_member, kernel_path, dry_run=dry_run)
    iso.extract_iso_member(iso_path, initrd_member, initrd_path, dry_run=dry_run)
    return kernel_path, initrd_path


def create_kickstart_iso(vm_name: str, vm: dict[str, Any], dry_run: bool = False) -> Path:
    artifact_dir = kickstart_artifact_dir(vm)
    cfg = render_kickstart(vm_name, vm)

    return cloud_init.create_iso_with_files(
        artifact_dir,
        {"ks.cfg": cfg},
        dry_run=dry_run,
        volume_id="KS_CFG",
    )


def kickstart_iso_drive_args(iso_path: Path) -> list[str]:
    return ["-drive", f"file={iso_path},format=raw,if=virtio,media=cdrom,readonly=on"]
