"""ReactOS unattended install: ``unattend.inf`` render, per-VM ISO rebuild (xorriso), CD-ROM args.

ReactOS Setup reads ``unattend.inf`` from its source root, ``\\I386`` on the BootCD (the copy under
``\\reactos`` belongs to the LiveCD); with ``UnattendSetupEnabled = yes`` both the text-mode stage
(partitioning, formatting, file copy) and the second GUI stage (owner, computer name, password,
time zone) run without a prompt, and ``[GuiRunOnce]`` runs commands at the first desktop logon.
The BootCD menu defaults to the Live environment, so the rebuilt ISO also carries a ``freeldr.ini``
whose default entry is ``Setup`` (verified live on 0.4.16).
"""
from __future__ import annotations

import hashlib
import re
import shutil
from pathlib import Path
from typing import Any

from vmctl import runtime, ui
from vmctl.errors import VMError


# The release kernel prints its debug log on COM1 whatever freeldr.ini says, and that port is the
# kernel debugger's: a user-mode ``echo > COM1`` from GuiRunOnce never reaches the host (verified
# live). The completion signal is therefore the kernel's own ACPI power-off line, printed exactly
# once, when the shutdown scheduled by the last GuiRunOnce command runs at the first desktop logon;
# the two Setup reboots in between are resets and never print it. A stuck Setup times out instead.
BOOTSTRAP_COMPLETE_TOKEN = "Entering sleep state S5"
# That power-off is the flush here: QEMU gets this long to exit on its own after the token.
SHUTDOWN_GRACE_SEC = 120
INSTALL_ISO_NAME = "install.iso"
# Setup reads the first; the LiveCD copy is replaced too so the medium tells one story.
UNATTEND_PATHS = ("/i386/unattend.inf", "/reactos/unattend.inf")
FREELDR_PATH = "/freeldr.ini"
SETUP_ENTRY = "Setup"
CD_DRIVE_ID = "roscd0"
INSTALLATION_TYPES = {"server": 0, "workstation": 1, "server-core": 2}
FS_TYPES = {"fat": 0, "btrfs": 1}


def reactos_config(vm: dict[str, Any]) -> dict[str, Any] | None:
    cfg = vm.get("reactos_config")
    if cfg is None:
        return None
    if not isinstance(cfg, dict):
        raise VMError("Invalid reactos_config: expected object")
    return cfg


def reactos_artifact_dir(vm: dict[str, Any]) -> Path:
    return runtime.resolve_path(vm["disk"]["path"]).parent / "reactos"


def install_iso_path(vm: dict[str, Any]) -> Path:
    return reactos_artifact_dir(vm) / INSTALL_ISO_NAME


def _inf_string(value: Any) -> str:
    text = str(value)
    if '"' in text or "\n" in text or "\r" in text:
        raise VMError(f"reactos_config values cannot contain quotes or newlines: {text!r}")
    return f'"{text}"'


def _lookup(table: dict[str, int], value: Any, field: str) -> int:
    if isinstance(value, bool):
        raise VMError(f"reactos_config.{field} must be a name or a number, not a boolean")
    if isinstance(value, int):
        if value not in table.values():
            raise VMError(f"reactos_config.{field}: unknown value {value}; choices: {', '.join(table)}")
        return value
    key = str(value).strip().lower()
    if key not in table:
        raise VMError(f"reactos_config.{field}: unknown value {value!r}; choices: {', '.join(table)}")
    return table[key]


def render_unattend(vm_name: str, vm: dict[str, Any]) -> str:
    """The ``unattend.inf`` of the ReactOS BootCD, every prompt of both Setup stages answered."""
    cfg = reactos_config(vm)
    if cfg is None:
        raise VMError("VM profile does not define reactos_config")
    password = str(cfg.get("password") or "")
    if not password:
        raise VMError("reactos_config.password is required (the answer file cannot take a hash)")
    fullname = str(cfg.get("fullname") or "Lab User").strip()
    computer_name = str(cfg.get("computer_name") or vm_name).strip().upper()[:15]
    if not re.fullmatch(r"[A-Z0-9-]+", computer_name):
        raise VMError(f"reactos_config.computer_name must be letters, digits and dashes: {computer_name!r}")
    locale_id = str(cfg.get("locale_id") or "409").strip()
    timezone_index = int(cfg.get("timezone_index", 85))
    installation_type = _lookup(INSTALLATION_TYPES, cfg.get("installation_type", "workstation"), "installation_type")
    fs_type = _lookup(FS_TYPES, cfg.get("fs_type", "fat"), "fs_type")
    install_dir = str(cfg.get("installation_directory") or "ReactOS").strip()
    run_once = [str(command) for command in (cfg.get("run_once") or [])]
    display = cfg.get("display") or {}
    if not isinstance(display, dict):
        raise VMError("reactos_config.display must be an object with XResolution/YResolution/BitsPerPel")

    lines = [
        f"; ReactOS unattend.inf generated by vmctl for {vm_name}",
        "[Unattend]",
        'Signature = "$ReactOS$"',
        "UnattendSetupEnabled = yes",
        "DestinationDiskNumber = 0",
        "DestinationPartitionNumber = 1",
        f"InstallationDirectory = {install_dir}",
        "; 2 = boot loader on the system partition (MBR + VBR)",
        "BootLoaderLocation = 2",
        f"FullName = {_inf_string(fullname)}",
        f"ComputerName = {_inf_string(computer_name)}",
        f"AdminPassword = {_inf_string(password)}",
        f"TimeZoneIndex = {timezone_index}",
        "DisableAutoDaylightTimeSet = 1",
        "; wipe and format the whole disk: the profile disk starts empty",
        "FormatPartition = 1",
        "AutoPartition = 1",
        f"FsType = {fs_type}",
        "RappsDownload = no",
        f"LocaleID = {locale_id}",
        f"InstallationType = {installation_type}",
        "",
        "; Runs at the first desktop logon (third boot): profile commands, then the guest's own",
        "; shutdown, whose ACPI power-off line on the kernel debug port is what the host waits for",
        "; (see CLAUDE.md, the token/flush rule: the power-off is the guest's, never the host's).",
        "[GuiRunOnce]",
        *run_once,
        "%SystemRoot%\\system32\\shutdown.exe /s /f /t 5",
    ]
    if display:
        lines += ["", "[Display]"]
        for key in ("BitsPerPel", "XResolution", "YResolution", "VRefresh"):
            if key in display:
                lines.append(f"{key} = {int(display[key])}")
    lines += ["", "[Shell]", "DefaultThemesOff = no",
              'CustomDefaultThemeFile = "%WINDIR%\\Resources\\Themes\\Lautus\\lautus.msstyles"', ""]
    return "\n".join(lines)


def render_freeldr(original: str, timeout_sec: int = 2) -> str:
    """The BootCD ``freeldr.ini`` with Setup as the default entry and a short timeout."""
    if f"[{SETUP_ENTRY}]" not in original:
        raise VMError(f"Incompatible ISO: freeldr.ini has no [{SETUP_ENTRY}] entry (not a ReactOS BootCD?)")
    text, n_default = re.subn(r"(?m)^DefaultOS=.*$", f"DefaultOS={SETUP_ENTRY}", original, count=1)
    text, n_timeout = re.subn(r"(?m)^TimeOut=.*$", f"TimeOut={int(timeout_sec)}", text, count=1)
    if not n_default or not n_timeout:
        raise VMError("Incompatible ISO: freeldr.ini has no DefaultOS/TimeOut keys in [FREELOADER]")
    return text


def _stamp(source_iso: Path, unattend: str) -> str:
    st = source_iso.stat()
    return f"{source_iso.resolve()}\n{st.st_size}\n{st.st_mtime_ns}\n{hashlib.sha256(unattend.encode()).hexdigest()}\n"


def ensure_install_iso(vm_name: str, vm: dict[str, Any], source_iso: Path, unattend: str, dry_run: bool = False) -> Path:
    """The per-VM unattended ISO under ``artifacts/<vm>/reactos/``, rebuilt when the source or the answers change.

    xorriso re-emits the whole image with the answer file and the patched boot menu grafted in and the
    original El Torito record replayed (``/loader/isoboot.bin``, no emulation): no extraction, no 7z.
    """
    dest = install_iso_path(vm)
    stamp_path = dest.with_name(dest.name + ".source")
    stamp = _stamp(source_iso, unattend) if source_iso.is_file() else None
    if dest.is_file() and stamp is not None and stamp_path.is_file() and stamp_path.read_text(encoding="utf-8") == stamp:
        ui.print_status("ok", f"Unattended ReactOS ISO ready: {ui.pretty_path(dest)}")
        return dest
    runtime.require_command("xorriso")
    ui.print_header("Build the unattended ReactOS ISO")
    ui.print_kv("source", ui.pretty_path(source_iso))
    ui.print_kv("target", ui.pretty_path(dest))
    work = reactos_artifact_dir(vm) / "iso-work"
    if work.exists() and not dry_run:
        shutil.rmtree(work)
    if not dry_run:
        work.mkdir(parents=True, exist_ok=True)
    freeldr_original = work / "freeldr.original.ini"
    runtime.run(["xorriso", "-osirrox", "on", "-indev", str(source_iso), "-extract", FREELDR_PATH, str(freeldr_original)],
                dry_run=dry_run, quiet=True)
    unattend_path = work / "unattend.inf"
    freeldr_path = work / "freeldr.ini"
    if not dry_run:
        freeldr_original.chmod(0o644)  # xorriso keeps the ISO's read-only mode
        freeldr_path.write_text(render_freeldr(freeldr_original.read_text(encoding="utf-8", errors="replace")), encoding="utf-8")
        unattend_path.write_text(unattend.replace("\n", "\r\n"), encoding="utf-8")
    partial = dest.with_name(dest.name + ".part")
    if not dry_run and partial.exists():
        partial.unlink()
    command = ["xorriso", "-indev", str(source_iso), "-outdev", str(partial), "-boot_image", "any", "replay"]
    for iso_member in UNATTEND_PATHS:
        command += ["-map", str(unattend_path), iso_member]
    command += ["-map", str(freeldr_path), FREELDR_PATH, "-commit"]
    runtime.run(command, dry_run=dry_run, quiet=True)
    if not dry_run:
        partial.replace(dest)
        shutil.rmtree(work, ignore_errors=True)
        if stamp is not None:
            stamp_path.write_text(stamp, encoding="utf-8")
    ui.print_status("ok", f"Unattended ReactOS ISO: {ui.pretty_path(dest)}")
    return dest


def install_media_args(iso_path: Path) -> list[str]:
    """The installer CD on the second IDE channel of the ``pc`` machine, after the disk in the boot order.

    Setup reboots twice (text stage, GUI stage); without ``-no-reboot`` the disk, once bootable,
    wins over the CD exactly like the Windows flow.
    """
    return [
        "-drive", f"id={CD_DRIVE_ID},file={iso_path},format=raw,if=none,media=cdrom,readonly=on",
        "-device", f"ide-cd,drive={CD_DRIVE_ID},bus=ide.1,bootindex=2",
    ]


def check_profile(vm_name: str, vm: dict[str, Any]) -> None:
    """What the ReactOS 0.4.16 release can boot: BIOS on the ``pc`` machine, a PATA disk, one CPU."""
    problems: list[str] = []
    if vm.get("firmware", {}).get("type") != "bios":
        problems.append("firmware.type must be bios (the release has no UEFI loader)")
    if str(vm.get("machine")) != "pc":
        problems.append("machine must be pc (the installer CD rides the PIIX IDE controller)")
    if vm.get("disk", {}).get("interface") != "ide":
        problems.append("disk.interface must be ide (no virtio or AHCI storage driver in the installer)")
    if int(vm.get("cpus", 1)) != 1:
        problems.append("cpus must be 1 (the release kernel is uniprocessor)")
    if problems:
        raise VMError(f"Profile '{vm_name}' cannot run the ReactOS unattended install: " + "; ".join(problems))
